name: Python Linting

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop

# Jobs
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint with flake8
        run: pipenv run flake8 --count --show-source --statistics
      - name: Lint with Pylint users app
        run: pipenv run pylint users accounts

