name: Python Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# Jobs
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Create env file
        run: |
          touch Bucketlist/.env
          echo "DATABASE_HOST=localhost" >> Bucketlist/.env
          echo "DATABASE_USER=bucketlist" >> Bucketlist/.env
          echo "DATABASE_PASS=bucketlist" >> Bucketlist/.env
          echo "DATABASE_NAME=bucketlist" >> Bucketlist/.env
          echo "SECRET_KEY=This-is-not-a-very-secure-key" >> Bucketlist/.env
      - name: Lint with flake8
        run: pipenv run flake8 --count --show-source --statistics
      - name: Lint with Pylint users app
        run: pipenv run pylint users accounts

